version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres-1crypten
    environment:
      POSTGRES_DB: trading_signals
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sD6*qY1@jV3^cK8#m10prasempre F5&g
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back/init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
      # - "5432:5432"  # Removido para evitar conflito de porta em produção
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis-1crypten
    # ports:
      # - "6379:6379"  # Removido para evitar conflito de porta em produção
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Flask API
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend-1crypten
    # ports:
      # - "5000:5000"  # Removido - acesso apenas via Nginx
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:sD6*qY1@jV3^cK8#m10prasempre F5&g@postgres:5432/trading_signals
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=gZ4vNpWq8sB2kF6a10prasempre
      - JWT_SECRET=X9&eR3@cM7!zL10prasempre 1*kP5^f
      - FLASK_PORT=5000
      - USE_BINANCE_API=true
      - BINANCE_API_KEY=aUApdM0jyXeyI1HPxHymi9hSD6QZ3TXFORTknlyc1jADrkCJ7SNSayoZ6oiPCYEj
      - BINANCE_SECRET_KEY=YGt2MXqsIhgjk6EsCwRCUjB3LpZ0L8xGAt9w4JYK6wyX2LveLHBFvRjoyBfIVcZM
      - TELEGRAM_BOT_TOKEN=7690455274:AAHB64l8csWoE5UpV1Pnn9c8chJzd5sZTXQ
      - TELEGRAM_CHAT_ID=1249100206
      - SENDPULSE_CLIENT_ID=7b28b045d31c3d6d51591d7f56a26c99
      - SENDPULSE_CLIENT_SECRET=26393054ce0cd24fc16a73382a3d5eef
      - SENDPULSE_SENDER_EMAIL=crypten@portaldigital10.com
      - POSTGRES_PASSWORD=sD6*qY1@jV3^cK8#m10prasempre F5&g
    volumes:
      - ./back/data:/app/data
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/api/health || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s

  # Frontend React App
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend-1crypten
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://1crypten.space
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend

  # Nginx Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-1crypten
    ports:
      - "3000:80"
    command: |
      sh -c '
      cat > /etc/nginx/nginx.conf << EOF
      events {
          worker_connections 1024;
      }
      
      http {
          include       /etc/nginx/mime.types;
          default_type  application/octet-stream;
          
          sendfile        on;
          keepalive_timeout  65;
          
          # Upstreams
          upstream backend {
              server backend:5000 max_fails=3 fail_timeout=30s;
          }
          
          upstream frontend {
              server frontend:80;
          }
          
          server {
              listen 80;
              server_name _;
              
              # Health check endpoint
              location /api/health {
                  proxy_pass http://backend/api/health;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Real-IP $$remote_addr;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $$scheme;
                  
                  # CORS headers
                  add_header Access-Control-Allow-Origin "*" always;
                  add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
                  add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization" always;
                  
                  # Handle preflight requests
                  if ($$request_method = OPTIONS) {
                      return 204;
                  }
                  
                  proxy_connect_timeout 60s;
                  proxy_send_timeout 60s;
                  proxy_read_timeout 60s;
                  proxy_next_upstream error timeout http_502 http_503 http_504;
              }
              
              # API routes
              location /api/ {
                  proxy_pass http://backend/api/;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Real-IP $$remote_addr;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $$scheme;
                  
                  # CORS headers
                  add_header Access-Control-Allow-Origin "*" always;
                  add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
                  add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization" always;
                  
                  # Handle preflight requests
                  if ($$request_method = OPTIONS) {
                      return 204;
                  }
                  
                  proxy_connect_timeout 120s;
                  proxy_send_timeout 600s;
                  proxy_read_timeout 600s;
                  
                  proxy_buffering off;
                  proxy_request_buffering off;
                  proxy_http_version 1.1;
                  proxy_set_header Connection "";
              }
              
              # Frontend routes
              location / {
                  proxy_pass http://frontend/;
                  proxy_set_header Host $$host;
                  proxy_set_header X-Real-IP $$remote_addr;
                  proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $$scheme;
                  
                  proxy_connect_timeout 30s;
                  proxy_send_timeout 30s;
                  proxy_read_timeout 30s;
              }
          }
      }
      EOF
      nginx -g "daemon off;"
      '
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local