version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///data/trading_signals.db
    volumes:
      - ./back/data:/app/data
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
    driver: local