version: '3.8'

services:
  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://1c30.com.br/api
    restart: unless-stopped